# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MedQuiz' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  
  # Pods for MedQuiz
  # https://github.com/rsrbk/SRCountdownTimer
  
  pod 'Firebase/Core'
  pod 'Firebase/Storage'
  pod 'FirebaseUI/Storage'
  pod 'Firebase/Database'
  
  target 'MedQuizTests' do
    inherit! :search_paths
    pod 'FBSnapshotTestCase'
    # Pods for testing
  end

  target 'MedQuizUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
